version: 2
  token: ${{secrets.DEPENDABOT_SECRET}}
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 20
  assignees:
  - christianh17
  versioning-strategy: increase
